### ISSUE TITLE
Readme is not clear- how to run package

### ISSUE THREAD

**Issue by pooraniravindhiran** [GMahmoud/virtual_costmap_layer#2]
How to run this package? How to input variables

**Comment by pooraniravindhiran** [comment]
An updated readme or tutorial would help a lot.

**Comment by GMahmoud** [comment]
@pooraniravi  Sorry I did not get the time to finish cleaning the v2.0 of this project (README included). However, I created a running sample that can help. 
https://github.com/GMahmoud/virtual_costmap_layer/blob/master/launch/sample.launch

By the end of this year I will finish this package and update the README.

Cheers

**Comment by ZDAHWYB** [comment]
Hello I got my inspiration from you,so i try to write a plugin. 
I wrote 

ros::Subscriber line_sub;
line_sub = nh.subscribe("line_layer", 100, LineCallback);

in the function onInitialize();
if i do not write ros::spin() ,it does not work;
but i had not found  ros::spin() in your code.
so please tell me the reason, thanks.

**Comment by arjunskumar** [comment]
Any idea on what parameters to be given for publishing the obstacles topics?

**Comment by GMahmoud** [comment]
Hi, @ZDAHWYB 
This ros package defines a [plugin](http://wiki.ros.org/pluginlib/Tutorials/Writing%20and%20Using%20a%20Simple%20Plugin) which can be used with a [`costmap_2d`](http://wiki.ros.org/costmap_2d). That's why there is no spinner or ros nodehandler in it.
For more information, you can find the definition of a costmap layer [here](https://github.com/ros-planning/navigation/blob/noetic-devel/costmap_2d/include/costmap_2d/layer.h) and even a costmap object will use the same node handler as the planner if I am not mistaken.
I put a [sample](https://github.com/GMahmoud/virtual_costmap_layer/blob/master/launch/sample.launch) to run `move_base` with this a `virtual_costmap_layer`.

**Comment by GMahmoud** [comment]
@arjunskumar 
Sorry I am afraid I did not understand well your question. 
However, if you are looking for obstacle message definition, you can find it in [this repo](https://github.com/GMahmoud/custom_msgs_demo/tree/demo/msg/virtual_layer)

**Comment by arjunskumar** [comment]
@GMahmoud I was able to build the package and its dependencies. But couldnt read the command for publishing properly from the gif . Could you add command for publishing virtual obstacles / zone ?. Also I tried this command 

```
rostopic pub /virtual_costamp_layer/obsctacles custom_msgs/Obstacles "list:
- form:
  - x: 1.0
    y: 1.0
    z: 0.0" 
```
